services:
  - type: web
    name: nova
    env: node
    rootDir: nova/backend
    buildCommand: |
      npm install
      cd ../frontend
      npm install
      npm run build
      cp -r build ../backend/frontend/
    startCommand: npm start
